### ISSUE TITLE
Cannot enlarge memory arrays. 

### ISSUE THREAD

**Issue by Christian-Yang** [compodoc/ngd#51]
after npm install  , I'm running    /root/node-v6.9.0-linux-x64/bin/ngd ,  then  get errors  as follow:

![Uploading 1.jpg…]()
![Uploading 2.jpg…]()

**Comment by Aorewen** [comment]
same here

**Comment by manekinekko** [comment]
this issue comes from the Viz dependency. We're trying another approach. Will keep you updated.

**Comment by manekinekko** [comment]
we're experimenting an other approach which would be rendering the graph on the client side (taking into account some performances issues).

**Comment by wgrabowski** [comment]
@manekinekko is this experimental approach somehow available (branch or something)?

**Comment by pantonis** [comment]
Have the same issue here? This thread is 10 months old. Any news?

**Comment by UnitedPE** [comment]
Same issue. Any news?

**Comment by manekinekko** [comment]
@vogloblinsky is working on a possible solution to fix this. 
To give you more context, this "solution" will allow rendering the graph deps on the client side (the user's browser). In fact, the library we depend on `viz.js` doesn't deal well with large projects. It simply crashes. In addition, it's not maintained anymore. 

In the meantime, we've included a "workaround" that simply skip the graph that are very large and don't render. You still should have the rest of the documentation generated and working properly (but without the affected graphs).

To do so, just run `compodoc` via `node`:

```
{
   "scripts": {
      "reports:doc": "node ./tools/scripts/compodoc.js"
   }
}
```

**Comment by DaSchTour** [comment]
@manekinekko I tried your solution but it doesn't work. It just throws an error
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn compodoc ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`
``

I also have no idea how this should work because compodoc is not registered as a binary anywere.

**Comment by vogloblinsky** [comment]
@DaSchTour the trick from @manekinekko is for compodoc installed globally in your system.

`npm i -g @compodoc/compodoc`

**Comment by AhHa45** [comment]
so this tool is useless?

**Comment by AhHa45** [comment]
running compodoc via a node script worked for me.

**Comment by ganqqwerty** [comment]
@AhHa45 how did you do that?

**Comment by cmxl** [comment]
any update on this?

**Comment by haris-begluk** [comment]
Same thing on windows, can't generate main diagram.
